# Generated by Django 2.2.13 on 2020-09-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerepo',
            name='processed_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagerepo',
            name='image_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
